version: '3'

services:
  https-portal:
    image: steveltn/https-portal:1
    ports:
      - 80:80
      - 443:443
    restart: always
    environment:
      DOMAINS: '[domain] -> http://nginx:8000'
      STAGE: production
    volumes:
      - ./org-chimata-ssl-certs:/var/lib/https-portal

  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "8000:8000"
    volumes:
      - ./nginx/conf:/etc/nginx/conf.d
      - ./nginx/uwsgi_params:/etc/nginx/uwsgi_params
      - ./src/static:/static
    environment:
      - SERVER_NAME=[domain]
    command: /bin/ash -c "envsubst < /etc/nginx/conf.d/nginx.conf.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
    depends_on:
      - web

  web:
    build: ./web
    container_name: web
    command: uwsgi --socket :8001 --module mysite.wsgi
    volumes:
      - ./src:/code
      - ./src/static:/static
    environment:
      - ENV=prd
    env_file:
      - .env
    expose:
      - "8001"
