version: '3'

# データベースのデータを永続化する
# 作成されたvolumeは docker volume ls で確認できる
volumes:
  dbdata:

services:
  sda-nginx:
    image: nginx:alpine
    container_name: sda-nginx
    ports:
      - "8000:8000"
    volumes:
      - ./nginx/conf:/etc/nginx/conf.d
      - ./nginx/uwsgi_params:/etc/nginx/uwsgi_params
      - ./src/static:/static
    environment:
      - SERVER_NAME=127.0.0.1
    command: /bin/ash -c "envsubst < /etc/nginx/conf.d/nginx.conf.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
    depends_on:
      - sda-web

  sda-db:
    image: postgres:11
    container_name: sda-db
    ports:
      - "5432:5432"
    volumes:
      - "dbdata:/var/lib/postgresql/data"
    environment:
      TZ: Asia/Tokyo
      POSTGRES_PASSWORD: password # settings.pyで設定した値と同じにする

  sda-web:
    build: ./web
    container_name: sda-web
    command: uwsgi --socket :8001 --module config.wsgi
    volumes:
      - ./src:/code
      - ./src/static:/static
    environment:
      - ENV=local
    expose:
      - "8001"
    depends_on:
      - sda-db